[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[nixpacks]
workdir = "backend"
